"""Reservation-based intersection conflict zone manager.

Pre-computes crossing points between all connection lane pairs and maintains a
reservation table so that at most one vehicle occupies each conflict zone at
any time.  Priority rules mirror real-world right-hand-traffic conventions:
    - Right-turners yield to straight-goers.
    - Left-turners yield to everyone.
    - Equal-priority ties are broken by vehicle-ID (lower ID wins).
"""

from __future__ import annotations

import math
from typing import Any, Dict, List, Optional, Set, Tuple

from src.core.enums import TurnIntent
from src.roads.lane import Lane

# ---------------------------------------------------------------------------
# Geometric helper
# ---------------------------------------------------------------------------

def _segment_intersection(
    p0: Tuple[float, float],
    p1: Tuple[float, float],
    p2: Tuple[float, float],
    p3: Tuple[float, float],
) -> Optional[Tuple[float, float]]:
    """Return the intersection point of segments p0→p1 and p2→p3, or *None*."""
    s1_x = p1[0] - p0[0]
    s1_y = p1[1] - p0[1]
    s2_x = p3[0] - p2[0]
    s2_y = p3[1] - p2[1]

    denom = -s2_x * s1_y + s1_x * s2_y
    if abs(denom) < 1e-9:
        return None

    s = (-s1_y * (p0[0] - p2[0]) + s1_x * (p0[1] - p2[1])) / denom
    t = (s2_x * (p0[1] - p2[1]) - s2_y * (p0[0] - p2[0])) / denom

    if 0.0 <= s <= 1.0 and 0.0 <= t <= 1.0:
        return (p0[0] + t * s1_x, p0[1] + t * s1_y)
    return None


def _distance_along_lane(lane: Lane, point: Tuple[float, float]) -> float:
    """Return the distance along *lane* from its start to *point*."""
    dx = point[0] - lane.start_coords[0]
    dy = point[1] - lane.start_coords[1]
    return math.sqrt(dx * dx + dy * dy)


# ---------------------------------------------------------------------------
# Conflict Zone data structures
# ---------------------------------------------------------------------------

class ConflictPoint:
    """A single crossing point between two connection lanes."""

    __slots__ = (
        "lane_id_a",
        "lane_id_b",
        "x",
        "y",
        "dist_on_a",
        "dist_on_b",
    )

    def __init__(
        self,
        lane_id_a: str,
        lane_id_b: str,
        x: float,
        y: float,
        dist_on_a: float,
        dist_on_b: float,
    ) -> None:
        self.lane_id_a = lane_id_a
        self.lane_id_b = lane_id_b
        self.x = x
        self.y = y
        self.dist_on_a = dist_on_a
        self.dist_on_b = dist_on_b


class Reservation:
    """Records which vehicle currently owns a conflict zone."""

    __slots__ = ("vehicle_id", "clear_time")

    def __init__(self, vehicle_id: str, clear_time: float) -> None:
        self.vehicle_id = vehicle_id
        self.clear_time = clear_time


# ---------------------------------------------------------------------------
# Turn-intent priority (higher number = higher priority = goes first)
# ---------------------------------------------------------------------------

_TURN_PRIORITY: Dict[TurnIntent, int] = {
    TurnIntent.STRAIGHT: 3,
    TurnIntent.RIGHT: 2,
    TurnIntent.LEFT: 1,
}


# ---------------------------------------------------------------------------
# ConflictManager
# ---------------------------------------------------------------------------

class ConflictManager:
    """Manages conflict detection and reservation for intersection crossing.

    Lifecycle
    ---------
    1. At simulation init, call :meth:`register_connection_lanes` with every
       connection lane generated by the road network.
    2. Call :meth:`compute_conflict_points` once to pre-compute all pairwise
       crossing points.
    3. Each tick, call :meth:`update_reservations` to expire stale locks, then
       :meth:`check_and_reserve` for each vehicle approaching the intersection
       to determine whether it may proceed.
    """

    # Safety buffer: distance (meters) before/after the conflict point that
    # counts as "in the zone"
    ZONE_RADIUS: float = 6.0

    # Time (seconds) a reservation persists after the vehicle has cleared
    CLEARANCE_TIME: float = 2.0

    def __init__(self) -> None:
        # All registered connection lanes, keyed by lane_id
        self._connection_lanes: Dict[str, Lane] = {}

        # Pre-computed conflict points:  (sorted-lane-pair) → ConflictPoint
        self._conflict_points: Dict[Tuple[str, str], ConflictPoint] = {}

        # Reservation table:  (sorted-lane-pair) → Reservation
        self._reservations: Dict[Tuple[str, str], Reservation] = {}

        # Mapping: connection_lane_id → set of conflict-pair keys it participates in
        self._lane_conflicts: Dict[str, Set[Tuple[str, str]]] = {}

    # ------------------------------------------------------------------
    # Setup
    # ------------------------------------------------------------------

    def register_connection_lane(self, lane: Lane) -> None:
        """Register a connection lane for conflict analysis."""
        self._connection_lanes[lane.lane_id] = lane

    def compute_conflict_points(self) -> None:
        """Pre-compute all pairwise crossing points between connection lanes."""
        lane_ids = list(self._connection_lanes.keys())
        self._conflict_points.clear()
        self._lane_conflicts.clear()

        for i in range(len(lane_ids)):
            for j in range(i + 1, len(lane_ids)):
                id_a = lane_ids[i]
                id_b = lane_ids[j]
                lane_a = self._connection_lanes[id_a]
                lane_b = self._connection_lanes[id_b]

                pt = _segment_intersection(
                    lane_a.start_coords,
                    lane_a.end_coords,
                    lane_b.start_coords,
                    lane_b.end_coords,
                )
                if pt is None:
                    continue

                key = (min(id_a, id_b), max(id_a, id_b))
                cp = ConflictPoint(
                    lane_id_a=key[0],
                    lane_id_b=key[1],
                    x=pt[0],
                    y=pt[1],
                    dist_on_a=_distance_along_lane(self._connection_lanes[key[0]], pt),
                    dist_on_b=_distance_along_lane(self._connection_lanes[key[1]], pt),
                )
                self._conflict_points[key] = cp

                self._lane_conflicts.setdefault(key[0], set()).add(key)
                self._lane_conflicts.setdefault(key[1], set()).add(key)

    # ------------------------------------------------------------------
    # Per-tick maintenance
    # ------------------------------------------------------------------

    def update_reservations(self, current_time: float) -> None:
        """Expire reservations whose clearance time has passed."""
        expired = [
            key
            for key, res in self._reservations.items()
            if current_time >= res.clear_time
        ]
        for key in expired:
            del self._reservations[key]

    def release_vehicle(self, vehicle_id: str) -> None:
        """Immediately release all reservations held by a vehicle (e.g. on exit)."""
        to_del = [
            key for key, res in self._reservations.items() if res.vehicle_id == vehicle_id
        ]
        for key in to_del:
            del self._reservations[key]

    # ------------------------------------------------------------------
    # Query / reservation
    # ------------------------------------------------------------------

    def get_conflict_distance(
        self,
        vehicle_id: str,
        vehicle_turn_intent: TurnIntent,
        connection_lane_id: str,
        vehicle_position_on_lane: float,
        current_time: float,
        all_vehicles_info: Optional[List[Dict[str, Any]]] = None,
    ) -> float:
        """Return the distance to the nearest *blocked* conflict zone, or inf.

        If the vehicle itself already holds the reservation, it is *not*
        blocked by its own lock.  If the zone is free (or can be acquired),
        the vehicle silently acquires it and returns inf.

        Parameters
        ----------
        vehicle_id : str
        vehicle_turn_intent : TurnIntent
        connection_lane_id : str
            The ``lane_id`` of the connection lane the vehicle is on or
            approaching.
        vehicle_position_on_lane : float
            How far along the connection lane the vehicle currently is.
        current_time : float
            Simulation clock time.
        all_vehicles_info : list, optional
            List of dicts with keys ``vehicle_id``, ``turn_intent``,
            ``connection_lane_id``, ``position_on_lane`` for all active
            vehicles currently on connection lanes. Used for priority
            arbitration when two vehicles approach the same zone simultaneously.

        Returns
        -------
        float
            Distance to the conflict point that blocks this vehicle, or
            ``float('inf')`` if the path is clear.
        """
        conflict_keys = self._lane_conflicts.get(connection_lane_id, set())
        if not conflict_keys:
            return float("inf")

        min_block_dist = float("inf")

        for key in conflict_keys:
            cp = self._conflict_points[key]

            # Distance of *this* vehicle to the conflict point
            if connection_lane_id == cp.lane_id_a:
                dist_to_cp = cp.dist_on_a
            else:
                dist_to_cp = cp.dist_on_b

            remaining = dist_to_cp - vehicle_position_on_lane

            # Vehicle has already passed this conflict point → skip
            if remaining < -self.ZONE_RADIUS:
                continue

            # Check existing reservation
            reservation = self._reservations.get(key)

            if reservation is not None:
                if reservation.vehicle_id == vehicle_id:
                    # We own it — no block
                    continue
                else:
                    # Someone else owns it — we must yield
                    block_dist = max(0.0, remaining - self.ZONE_RADIUS)
                    min_block_dist = min(min_block_dist, block_dist)
                    continue

            # No reservation — attempt to acquire if we're close enough to
            # care (within 2× zone radius of the conflict point)
            if remaining <= self.ZONE_RADIUS * 2:
                # Check if another vehicle is also approaching this zone
                should_yield = False

                if all_vehicles_info:
                    for other_info in all_vehicles_info:
                        other_id = other_info["vehicle_id"]
                        if other_id == vehicle_id:
                            continue

                        other_conn = other_info.get("connection_lane_id", "")
                        if other_conn not in (cp.lane_id_a, cp.lane_id_b):
                            continue
                        if other_conn == connection_lane_id:
                            # Same lane — handled by lane-following, not conflict zones
                            continue

                        # Other vehicle is on the *other* lane of this conflict pair
                        if other_conn == cp.lane_id_a:
                            other_dist_to_cp = cp.dist_on_a
                        else:
                            other_dist_to_cp = cp.dist_on_b

                        other_pos = other_info.get("position_on_lane", 0.0)
                        other_remaining = other_dist_to_cp - other_pos

                        # Only consider if other vehicle is also approaching
                        if other_remaining < -self.ZONE_RADIUS:
                            continue

                        # Priority arbitration
                        other_turn = other_info.get("turn_intent", TurnIntent.STRAIGHT)
                        my_priority = _TURN_PRIORITY.get(vehicle_turn_intent, 2)
                        other_priority = _TURN_PRIORITY.get(other_turn, 2)

                        if other_priority > my_priority:
                            should_yield = True
                            break
                        elif other_priority == my_priority:
                            # Tiebreak: lower vehicle ID wins
                            if other_id < vehicle_id:
                                should_yield = True
                                break

                if should_yield:
                    block_dist = max(0.0, remaining - self.ZONE_RADIUS)
                    min_block_dist = min(min_block_dist, block_dist)
                else:
                    # Acquire reservation
                    clear_time = current_time + self.CLEARANCE_TIME + 5.0  # generous default
                    self._reservations[key] = Reservation(vehicle_id, clear_time)

        return min_block_dist

    def update_reservation_clear_time(
        self, vehicle_id: str, connection_lane_id: str, current_time: float
    ) -> None:
        """Update the clearance time for reservations held by a vehicle that
        has passed through the conflict point (so they expire promptly)."""
        conflict_keys = self._lane_conflicts.get(connection_lane_id, set())
        for key in conflict_keys:
            res = self._reservations.get(key)
            if res is not None and res.vehicle_id == vehicle_id:
                # cp = self._conflict_points[key]  # removed unused variable
                # Set a tight clearance window
                res.clear_time = current_time + self.CLEARANCE_TIME

    def get_all_conflict_points(self) -> List[ConflictPoint]:
        """Return all pre-computed conflict points (useful for debugging/visualization)."""
        return list(self._conflict_points.values())

    def get_reservation_count(self) -> int:
        """Return the number of active reservations."""
        return len(self._reservations)
